changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Features
      labels:
        - enhancement
        - feat
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Infrastructure
      labels:
        - ci
        - docker
        - dependencies
    - title: Other Changes
      labels:
        - "*"

