packages:
  - "apps/*"
  - "packages/*"
  - "workers/*"

pnpm:
  overrides:
    prisma: 6.19.3
    "@prisma/client": 6.19.3

supportedArchitectures:
  os:
    - linux
    - current
  cpu:
    - x64
    - current
  libc:
    - musl
    - glibc
    - current
