const AUDIT_ACTION_LABELS: Record<string, string> = {
  'post.approve': 'تأیید آگهی',
  'post.reject': 'رد آگهی',
  'post.update': 'ویرایش آگهی',
  'post.delete': 'حذف آگهی',
  'post.forcePromote': 'نردبان اجباری',
  'post.forceExpire': 'انقضای اجباری',
  'user.ban': 'مسدودسازی کاربر',
  'user.unban': 'رفع مسدودی',
  'user.verify': 'تأیید کاربر',
  'user.edit': 'ویرایش کاربر',
  'user.role.set': 'تغییر نقش',
  'user.karma': 'تنظیم کارما',
  'user.business.grant': 'ارتقا به فروشگاهی',
  'user.business.revoke': 'لغو فروشگاهی',
  'wallet.credit': 'شارژ کیف پول',
  'wallet.debit': 'برداشت کیف پول',
  'story.delete': 'حذف استوری',
  'storyComment.delete': 'حذف کامنت استوری',
  'comment.delete': 'حذف کامنت',
  'payment.refund': 'بازگشت پرداخت',
  'broadcast.send': 'اعلان همگانی',
  'block.remove': 'حذف مسدودی',
  'message.delete': 'حذف پیام',
  'notification.delete': 'حذف اعلان',
  'notification.system': 'اعلان سیستمی',
  'push.revoke': 'لغو اشتراک push',
  'highlight.update': 'ویرایش هایلایت',
  'highlight.delete': 'حذف هایلایت',
  'searchAlert.delete': 'حذف هشدار جستجو',
  'follow.remove': 'حذف دنبال‌کردن',
  'like.remove': 'حذف لایک',
  'live.end': 'پایان لایو',
  'payout.approve': 'تأیید تسویه',
  'payout.reject': 'رد تسویه',
  'payout.paid': 'پرداخت تسویه',
  'settings.update': 'به‌روزرسانی تنظیمات',
  'system.reindex': 'بازنمایه‌سازی',
  'system.reindex-stories': 'بازنمایه استوری',
  'system.queues.clean': 'پاکسازی صف',
  'category.create': 'ایجاد دسته',
  'category.update': 'ویرایش دسته',
  'category.delete': 'حذف دسته',
  'category.attribute.create': 'ایجاد ویژگی',
  'category.attribute.update': 'ویرایش ویژگی',
  'category.attribute.delete': 'حذف ویژگی',
  'province.create': 'ایجاد استان',
  'province.update': 'ویرایش استان',
  'province.delete': 'حذف استان',
  'city.create': 'ایجاد شهر',
  'city.update': 'ویرایش شهر',
  'city.delete': 'حذف شهر',
  'neighborhood.create': 'ایجاد محله',
  'neighborhood.update': 'ویرایش محله',
  'neighborhood.delete': 'حذف محله',
  'boostPlan.create': 'ایجاد پلن نردبان',
  'boostPlan.update': 'ویرایش پلن نردبان',
  'boostPlan.deactivate': 'غیرفعال‌سازی پلن',
  'boostPlan.delete': 'حذف پلن نردبان',
  'report.dismiss': 'رد گزارش',
  'report.resolve': 'حل گزارش',
  'report.delete': 'حذف گزارش',
};

/** Persian label for an audit-log action code (falls back to the raw code). */
export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action;
}
